sim_human_a:
  ros__parameters:
    agent_id: "human_a"
    goal_property: "X"
    server_base_url: "http://172.17.40.64:8080"
    stt_topic: "/audio/stt_text"

    policy_type: "llm"
    llm_provider: "openai"
    llm_model: "gpt-4.1-mini"
    llm_temperature: 0.25
    llm_max_tokens: 250
    llm_top_k_boxes: 100
    llm_timeout_sec: 30.0

    humans_json: >
      [{"id":"human_a","name":"Sam"},{"id":"human_b","name":"Jacob"}]
    robots_json: >
      [{"id":"robot","name":"Bob"}]

    trust_overrides_json: >
      {"human_b": 0.55, "robot": 0.65}

    help_target_speaker: "robot"
    decision_period_sec: 1.0
    speed_mps: 1.15
    dist_weight: 2.4
    log_actions: true

    # --- more decisive / self-focused ---
    risk_aversion: 0.30
    stubbornness: 0.70
    fairness_sensitivity: 0.20

    # willing to act sooner
    dispose_threshold: 0.74
    giveup_threshold: 0.30
    help_wait_sec: 28.0
    help_cooldown_sec: 14.0



sim_human_b:
  ros__parameters:
    agent_id: "human_b"
    goal_property: "Y"
    server_base_url: "http://172.17.40.64:8080"
    stt_topic: "/audio/stt_text"

    policy_type: "llm"
    llm_provider: "openai"
    llm_model: "gpt-4.1-mini"
    llm_temperature: 0.10
    llm_max_tokens: 250
    llm_top_k_boxes: 100
    llm_timeout_sec: 30.0

    humans_json: >
      [{"id":"human_a","name":"Sam"},{"id":"human_b","name":"Jacob"}]
    robots_json: >
      [{"id":"robot","name":"Bob"}]

    trust_overrides_json: >
      {"human_a": 0.70, "robot": 0.70}

    help_target_speaker: "human_a"
    decision_period_sec: 1.0
    speed_mps: 0.95
    dist_weight: 1.6
    log_actions: true

    # --- cautious / cooperative ---
    risk_aversion: 0.90
    stubbornness: 0.20
    fairness_sensitivity: 0.85

    # demands more certainty, but doesn't give up quickly
    dispose_threshold: 0.88
    giveup_threshold: 0.12
    help_wait_sec: 14.0
    help_cooldown_sec: 6.0



